linters:
  enable:
    - errcheck
    - errorlint
    - cyclop
    - errname
    - exhaustive
    - copyloopvar
    - gocritic
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unused
    - ginkgolinter
run:
  go: "1.22"
linters-settings:
  gocritic:
    enabled-checks:
      - hugeParam
      - rangeExprCopy
      - rangeValCopy
      - indexAlloc
    settings:
      ifElseChain:
        minThreshold: 3
  cyclop:
    max-complexity: 150 # TODO: reduce that to 20
