apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: netobserv-cli
  namespace: "{{NAMESPACE}}"
  labels:
    app: netobserv-cli
spec:
  selector:
    matchLabels:
      app: netobserv-cli
  template:
    metadata:
      labels:
        app: netobserv-cli
    spec:
      serviceAccountName: netobserv-cli
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
      - operator: Exists
      containers:
      - name: netobserv-cli
        image: "{{AGENT_IMAGE_URL}}"
        imagePullPolicy: Always
        securityContext:
          privileged: true
          runAsUser: 0
        env:
          - name: METRICS_ENABLE
            value: "false"
          - name: LOG_LEVEL
            value: info
          - name: INTERFACES
            value: ""
          - name: EXCLUDE_INTERFACES
            value: "lo"
          - name: SAMPLING
            value: "1"
          - name: ENABLE_RTT
            value: "false"
          - name: ENABLE_PKT_DROPS
            value: "false"
          - name: ENABLE_DNS_TRACKING
            value: "false"
          - name: ENABLE_NETWORK_EVENTS_MONITORING
            value: "false"
          - name: ENABLE_UDN_MAPPING
            value: "false"
          - name: ENABLE_PKT_TRANSLATION
            value: "false"
          - name: ENABLE_FLOW_FILTER
            value: "false"
          - name: FLOW_FILTER_RULES
            value: >-
              []
          - name: EXPORT
            value: "direct-flp"
          - name: FLP_CONFIG
            value: |
              {}
        volumeMounts:
            - name: bpf-kernel-debug
              mountPath: /sys/kernel/debug
              mountPropagation: Bidirectional
            - name: var-run-ovn
              mountPath: /var/run/ovn
              mountPropagation: Bidirectional
            - name: var-run-ovs
              mountPath: /var/run/openvswitch
              mountPropagation: Bidirectional
            - name: var-run-netns
              mountPath: /var/run/netns
              mountPropagation: Bidirectional
      volumes:
        - name: bpf-kernel-debug
          hostPath:
            path: /sys/kernel/debug
            type: Directory
        - name: var-run-ovn
          hostPath:
            path: /var/run/ovn-ic
            type: DirectoryOrCreate
        - name: var-run-ovs
          hostPath:
            path: /var/run/openvswitch
            type: DirectoryOrCreate
        - name: var-run-netns
          hostPath:
            path: /var/run/netns
            type: Directory
