apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: netobserv-cli
  namespace: "{{NAMESPACE}}"
  labels:
    app: netobserv-cli
spec:
  selector:
    matchLabels:
      app: netobserv-cli
  template:
    metadata:
      labels:
        app: netobserv-cli
    spec:
      serviceAccountName: netobserv-cli
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: netobserv-cli
        image: "{{AGENT_IMAGE_URL}}"
        imagePullPolicy: Always
        securityContext:
          privileged: true
          runAsUser: 0
        env:
          - name: METRICS_ENABLE
            value: "false"
          - name: LOG_LEVEL
            value: info
          - name: INTERFACES
            value: ""
          - name: EXCLUDE_INTERFACES
            value: "lo"
          - name: SAMPLING
            value: "1"
          - name: ENABLE_RTT
            value: "false"
          - name: ENABLE_PKT_DROPS
            value: "false"
          - name: ENABLE_DNS_TRACKING
            value: "false"
          - name: ENABLE_NETWORK_EVENTS_MONITORING
            value: "false"
          - name: ENABLE_FLOW_FILTER
            value: "false"
          - name: FLOW_FILTER_RULES
            value: >
              [ { "direction": "", "ip_cidr": "0.0.0.0/0", "protocol": "", "source_port": 0,
                "destination_port": 0, "port": 0, "source_port_range": "",
                "source_ports": "", "destination_port_range": "",
                "destination_ports": "", "port_range": "", "ports": "",
                "icmp_type": 0, "icmp_code": 0, "peer_ip": "", "peer_cidr": "", action": "Accept",
                "tcp_flags": "", "drops": false } 
              ]
          - name: EXPORT
            value: "direct-flp"
          - name: FLP_CONFIG
            value: >
              {
                "log-level": "trace",
                "metricsSettings":{
                    "disableGlobalServer": true
                },
                "parameters":[
                    {
                      "name":"enrich",
                      "transform":{
                          "type":"network",
                          "network":{
                            "rules":[
                                {
                                  "type":"add_kubernetes",
                                  "kubernetes":{
                                      "add_zone": true,
                                      "ipField":"SrcAddr",
                                      "output":"SrcK8S"
                                  }
                                },
                                {
                                  "type":"add_kubernetes",
                                  "kubernetes":{
                                      "add_zone": true,
                                      "ipField":"DstAddr",
                                      "output":"DstK8S"
                                  }
                                },
                                {
                                  "type":"reinterpret_direction"
                                }
                            ],
                            "directionInfo":{
                                "reporterIPField":"AgentIP",
                                "srcHostField":"SrcK8S_HostIP",
                                "dstHostField":"DstK8S_HostIP",
                                "flowDirectionField":"FlowDirection"
                            }
                          }
                      }
                    },
                    {
                      "name":"send",
                      "write":{
                          "type":"grpc",
                          "grpc":{
                            "targetHost":"{{TARGET_HOST}}",
                            "targetPort":9999
                          }
                      }
                    }
                ],
                "pipeline":[
                    {
                      "name":"enrich",
                      "follows":"preset-ingester"
                    },
                    {
                      "name":"send",
                      "follows":"enrich"
                    }
                ]
              }
        volumeMounts:
            - name: bpf-kernel-debug
              mountPath: /sys/kernel/debug
              mountPropagation: Bidirectional
            - name: var-run-ovn
              mountPath: /var/run/ovn
              mountPropagation: Bidirectional
            - name: var-run-ovs
              mountPath: /var/run/openvswitch
              mountPropagation: Bidirectional
            - name: var-run-netns
              mountPath: /var/run/netns
              mountPropagation: Bidirectional
      volumes:
        - name: bpf-kernel-debug
          hostPath:
            path: /sys/kernel/debug
            type: Directory
        - name: var-run-ovn
          hostPath:
            path: /var/run/ovn-ic
            type: DirectoryOrCreate
        - name: var-run-ovs
          hostPath:
            path: /var/run/openvswitch
            type: DirectoryOrCreate
        - name: var-run-netns
          hostPath:
            path: /var/run/netns
            type: Directory
