apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: netobserv-cli
  namespace: "{{NAMESPACE}}"
  labels:
    app: netobserv-cli
spec:
  selector:
    matchLabels:
      app: netobserv-cli
  template:
    metadata:
      labels:
        app: netobserv-cli
    spec:
      serviceAccountName: netobserv-cli
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
      - operator: Exists
      containers:
      - name: netobserv-cli
        image: "{{AGENT_IMAGE_URL}}"
        imagePullPolicy: Always
        securityContext:
          privileged: true
          runAsUser: 0
        env:
          - name: CACHE_ACTIVE_TIMEOUT
            value: "1s"
          - name: ENABLE_PCA
            value: "true"
          - name: METRICS_ENABLE
            value: "false"
          - name: LOG_LEVEL
            value: info
          - name: FLOW_FILTER_RULES
            value: >-
              []
          - name: TC_ATTACH_MODE
            value: "any"
          - name: EXPORT
            value: "direct-flp"
          - name: FLP_CONFIG
            value: |
              {}
        volumeMounts:
            - name: bpf-kernel-debug
              mountPath: /sys/kernel/debug
              mountPropagation: Bidirectional
      volumes:
        - name: bpf-kernel-debug
          hostPath:
            path: /sys/kernel/debug
            type: Directory
