#!/bin/bash
source "./scripts/functions.sh"

# interface filter such as 'br-ex'
filter=""

if [ -z "${1:-}" ]
then
  echo "Filters not set"
else
  echo "Filters set as $1"
  filter=$1
fi

trap cleanup EXIT

setup flows $filter

echo "\nRunning network-observability-cli get-flows... "
oc run \
  -n netobserv-cli \
  collector \
  --image=quay.io/jpinsonn/network-observability-cli:dev \
  --image-pull-policy='Always' \
  --restart='Never' \
  --command -- sleep infinity

oc wait \
  -n netobserv-cli \
  --for=condition=Ready pod/collector

oc exec -i --tty \
  -n netobserv-cli \
  collector \
  -- /network-observability-cli get-flows ${filter:+"--filter" "$filter"}