#!/bin/bash
source "${BASH_SOURCE%/*}/network-observability-cli-resources/functions.sh"

# interface filter such as 'br-ex'
filter=""

if [ -z "${1:-}" ]
then
  echo "Filters not set"
else
  echo "Filters set as $1"
  filter=$1
fi

trap cleanup EXIT

setup flows $filter

echo "\nRunning network-observability-cli get-flows... "
${BASH_SOURCE%/*}/network-observability-cli --nodes $nodes --ports $ports ${filter:+"--filter" "$filter"} get-flows
