#!/bin/bash
source "./scripts/functions.sh"

# interface filter such as 'br-ex'
filter=""

if [ -z "${1:-}" ]
then
  echo "Filters not set"
else
  echo "Filters set as $1"
  filter=$1
fi

# CLI image to use
img="quay.io/mmahmoud/network-observability-cli:main-amd64"

trap cleanup EXIT

setup flows $filter

echo "Running network-observability-cli get-flows-db... "
oc run \
  -n netobserv-cli \
  collector \
  --image=$img\
  --image-pull-policy='Always' \
  --restart='Never' \
  --command -- sleep infinity

oc wait \
  -n netobserv-cli \
  --for=condition=Ready pod/collector

oc exec -i --tty \
  -n netobserv-cli \
  collector \
  -- /network-observability-cli get-flows-db ${filter:+"--filter" "$filter"}
