#!/bin/bash
source "./scripts/functions.sh"

# pcap filter such as 'tcp,80'
filter=""

if [ -z "${1:-}" ]
then
  echo "Specify a valid filter as first argument such as 'oc get-packets tcp,80'"
  exit 1
else
  echo "Filters set as $1"
  filter=$1
fi

# CLI image to use
img="quay.io/netobserv/network-observability-cli:main"

trap cleanup EXIT

setup packets $filter

echo "\nRunning network-observability-cli get-packets... "
oc run \
  -n netobserv-cli \
  collector \
  --image=$img \
  --image-pull-policy='Always' \
  --restart='Never' \
  --command -- sleep infinity

oc wait \
  -n netobserv-cli \
  --for=condition=Ready pod/collector

oc exec -i --tty \
  -n netobserv-cli \
  collector \
  -- /network-observability-cli get-packets --filter "$filter"