#!/bin/bash
source "./scripts/functions.sh"

set +u

# e2e skips inputs
if [ -z "${isE2E+x}" ]; then isE2E=false; fi
# keep capture state
if [ -z "${captureStarted+x}" ]; then captureStarted=false; fi
# prompt copy by default
if [ -z "${copy+x}" ]; then copy="prompt"; fi

# interface filter such as 'br-ex' or pcap filter such as 'tcp,80'
filter=""

# CLI image to use
img="quay.io/netobserv/network-observability-cli:main"

if [ -n "$NETOBSERV_COLLECTOR_IMAGE" ]; then
  echo "using custom collector image $NETOBSERV_COLLECTOR_IMAGE"
  img="$NETOBSERV_COLLECTOR_IMAGE"
fi

# version to display
version="0.0.1"

# command to run
command=""

# log level (default: info)
logLevel="info"

# max time (default: 5min)
maxTime="5m" 

# max bytes (default: 50MB)
maxBytes=50000000

function flows() {
  case "$2" in
    "help")
      flows_usage
      exit 0 ;;
    *)
      shift # remove first argument
      filter="$*"
      # run flows command
      command="flows" ;;
  esac
}

function packets() {
  case "$2" in
    "help")
      packets_usage
      exit 0 ;;
    *)
      shift # remove first argument
      filter="$*"
      # run packets command
      command="packets" ;;
  esac
}

case "$1" in  
"help")
    # display Help
    echo
    echo "Netobserv allows you to capture flow and packets from your cluster."
    echo "Find more information at: https://github.com/netobserv/network-observability-cli/"
    echo
    echo "Syntax: netobserv [flows|packets|cleanup] [options]"
    echo
    echo "commands:"
    echo "  flows      Capture flows information. You can specify an optional interface name as filter such as 'netobserv flows br-ex'."
    echo "        Options:"
    flows_usage
    echo "  packets    Capture packets information in pcap format."
    echo "        Options:"
    packets_usage
    echo "  cleanup    Remove netobserv components."
    echo "  version    Print software version."
    echo
    exit 0 ;;
"version")
    # display version
    echo "Netobserv CLI version $version"
    exit 0 ;;
"flows")
    flows $* ;;
"packets")
    packets $* ;;
"cleanup")
    # run cleanup command
    cleanup
    exit 0 ;;
*)
    echo "Unknown command $1. Use 'netobserv help' to display options"
    exit 1
esac

trap cleanup EXIT

setup $command $filter

echo "Running network-observability-cli get-$command... "
${K8S_CLI_BIN} run \
  -n netobserv-cli \
  collector \
  --image=$img\
  --image-pull-policy='Always' \
  --restart='Never' \
  --command -- sleep infinity

${K8S_CLI_BIN} wait \
  -n netobserv-cli \
  --for=condition=Ready pod/collector || exit 1

captureStarted=true

${K8S_CLI_BIN} exec -i --tty \
  -n netobserv-cli \
  collector \
  -- /network-observability-cli get-$command ${filter:+"--filter" "${filter//--/}"} --loglevel $logLevel --maxtime $maxTime --maxbytes $maxBytes