#!/bin/bash
source "./scripts/functions.sh"

set +u

# interface filter such as 'br-ex' or pcap filter such as 'tcp,80'
filter=""

# CLI image to use
img="quay.io/netobserv/network-observability-cli:main"

if [ -n "$NETOBSERV_COLLECTOR_IMAGE" ]; then
  echo "using custom collector image $NETOBSERV_COLLECTOR_IMAGE"
  img="$NETOBSERV_COLLECTOR_IMAGE"
fi

# version to display
version="0.0.1"

# command to run
command=""

case "$1" in  
"help")
    # display Help
    echo
    echo "Netobserv allows you to capture flow and packets from your cluster."
    echo "Find more information at: https://github.com/netobserv/network-observability-cli/"
    echo
    echo "Syntax: netobserv [flows|packets|cleanup] [filters]"
    echo
    echo "options:"
    echo "  flows      Capture flows information. You can specify an optional interface name as filter such as 'netobserv flows br-ex'."
    flows_usage
    echo "  packets    Capture packets information in pcap format."
    packets_usage
    echo "  cleanup    Remove netobserv components."
    echo "  version    Print software version."
    echo
    exit 0 ;;
"version")
    # display version
    echo "Netobserv CLI version $version"
    exit 0 ;;
"flows")
    shift # remove first argument
    filter="$*"
    # run flows command
    command="flows" ;;
"packets")
    shift # remove first argument
    filter="$*"
    # run packets command
    command="packets" ;;
"cleanup")
    # run cleanup command
    cleanup
    exit 0 ;;
*)
    echo "Unknown command $1. Use 'netobserv help' to display options"
    exit 1
esac

trap cleanup EXIT

setup $command $filter

echo "Running network-observability-cli get-$command... "
${K8S_CLI_BIN} run \
  -n netobserv-cli \
  collector \
  --image=$img\
  --image-pull-policy='Always' \
  --restart='Never' \
  --command -- sleep infinity

${K8S_CLI_BIN} wait \
  -n netobserv-cli \
  --for=condition=Ready pod/collector

${K8S_CLI_BIN} exec -i --tty \
  -n netobserv-cli \
  collector \
  -- /network-observability-cli get-$command ${filter:+"--filter" "$filter"}