#!/bin/bash
ADOC=./docs/netobserv_cli.adoc

# Header
echo "// Automatically generated by '$0'. Do not edit, or make the NETOBSERV team aware of the editions.
:_mod-docs-content-type: REFERENCE
[id=\"network-observability-cli-usage_{context}\"]
= Network Observability CLI usage

Users of Netobserv CLI can pass command line arguments to enable features or pass configuration options to the eBPF agent and flowlogs-pipeline.
This document lists all the supported command line options and their possible values.
" > $ADOC

# Flow table
{
echo "== Flows usage
[cols=\"1,1,1\",options=\"header\"]
|===
| Option | Description | Default"
./build/oc-netobserv flows help
echo -e "|==="
# Flow example
echo "
Example running flow capture with some options:
\`\`\`
oc netobserv flows --enable_pktdrop=true  --enable_rtt=true --enable_filter=true --action=Accept --cidr=0.0.0.0/0 --protocol=TCP --port=49051
\`\`\`"

# Packet table
echo "== Packets usage
[cols=\"1,1,1\",options=\"header\"]
|===
| Option | Description | Default"
./build/oc-netobserv packets help
echo -e "|==="
# Packet example
echo "
Example running packet capture with some options:
\`\`\`
oc netobserv packets --action=Accept --cidr=0.0.0.0/0 --protocol=TCP --port=49051
\`\`\`"
} >> $ADOC

# remove double spaces
sed -i.bak "s/  */ /" $ADOC
# add table rows
sed -i.bak "/^ /s/ --*/|--/" $ADOC
# add table columns
sed -i.bak "/^|/s/(default:/|/" $ADOC
sed -i.bak "/^|/s/: /|/" $ADOC
sed -i.bak "/^|/s/)//" $ADOC

rm ./docs/*.bak
