name: Build PR image and upload artifact
on:
  pull_request:
    types: [labeled]

env:
  WF_REGISTRY: quay.io/netobserv
  WF_IMAGE: network-observability-cli

permissions:
  contents: read

jobs:
  build-pr-image:
    if: ${{ github.event.label.name == 'ok-to-test' }}
    name: Build PR image and upload artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
        with:
          persist-credentials: false
      - name: Install make
        run: sudo apt -y install make
      - name: build and save image
        run: OCI_BUILD_OPTS="--label quay.expires-after=2w" IMAGE=${{ env.WF_REGISTRY }}/${{ env.WF_IMAGE }}:tmp CLEAN_BUILD=1 make tar-image
      - name: make commands
        run: |
          head_sha="${{ github.event.pull_request.head.sha }}"
          USER=netobserv VERSION=${head_sha::8} make commands
      - name: upload commands
        id: artifact-upload-step
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: commands
          path: build/
      - name: save commands URL
        run: |
          echo ${{ steps.artifact-upload-step.outputs.artifact-url }} > ./out/commands-url
      - name: upload artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: pr
          path: out/
