name: on new release
on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  update-krew:
    name: update krew
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Call krew-release-bot
        uses: rajatjindal/krew-release-bot@3d9faef30a82761d610544f62afddca00993eef9 # v0.0.47
